export type * from "./type/TermMapping.js"
export type * from "./type/TermWrapperConstructor.js"
export type * from "./type/ValueMapping.js"

export * from "./decorators/GetterArity.js"
export * from "./decorators/SetterArity_.js"
export * from "./decorators/getter.js"
export * from "./decorators/setter.js"
export * from "./mapping/TermMappings.js"
export * from "./mapping/ValueMappings.js"
export * from "./DatasetWrapper.js"
export * from "./TermWrapper.js"
